<a href="https://colab.research.google.com/github/jeongaaaa/multicampus_25th/blob/master/05_Machine%20Learning/1_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3])

print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [3]:
array2 = np.array([[1, 2, 3], [2, 3, 4]])

print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [5]:
array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [6]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [7]:
array4 = np.array([[[1, 2, 3],[2, 3, 4]], [[1, 2, 3],[2, 3, 4]]])
print('array4 type:', type(array4))
print('array4 array 형태:', array4.shape)

array4 type: <class 'numpy.ndarray'>
array4 array 형태: (2, 2, 3)


In [8]:
array_2x2 = np.array([[1,2], [3,4]])
print('array_2x2 array 형태:', array_2x2.shape)

array_3x3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print('array_3x3 array 형태:', array_3x3.shape)

matrix_3x3_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_3x3_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_3x3_3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_3x3_4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

m1_2x2_of_3x3 = np.array([[matrix_3x3_1, matrix_3x3_2],
                          [matrix_3x3_3, matrix_3x3_4]])

print('m1_2x2_of_3x3 array 형태:', m1_2x2_of_3x3.shape)

m2_2x2_of_3x3 = np.array([[[[1,2,3],[4,5,6],[7,8,9]],
                      [[1,2,3],[4,5,6],[7,8,9]]],
                      [[[1,2,3],[4,5,6],[7,8,9]],
                      [[1,2,3],[4,5,6],[7,8,9]]]])

print('m2_2x2_of_3x3 array 형태:', m2_2x2_of_3x3.shape)

array_2x2 array 형태: (2, 2)
array_3x3 array 형태: (3, 3)
m1_2x2_of_3x3 array 형태: (2, 2, 3, 3)
m2_2x2_of_3x3 array 형태: (2, 2, 3, 3)


In [9]:
m1_2x2_of_3x3

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [10]:
m2_2x2_of_3x3

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [11]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원, array4: {3}차원'.format(array1.ndim,array2.ndim,array3.ndim,array4.ndim))
print('m2_2x2_of_3x3: {0}차원, m2_2x2_of_3x3: {1}차원'.format(m1_2x2_of_3x3.ndim,m2_2x2_of_3x3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원, array4: 3차원
m2_2x2_of_3x3: 4차원, m2_2x2_of_3x3: 4차원


##ndarray의 데이터 타입

In [12]:
list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))

print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


####서로 다른 데이터 타입이 들어올 경우 더 큰 데이터 타입으로 변환

In [15]:
list2 = [1, 2, 'text']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'text'] <U21


In [14]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


####ndarray 내 데이터 타입 변경

In [16]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') 
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [17]:
array_int1= array_float.astype('int64') 
print(array_int1, array_int1.dtype)

[1 2 3] int64


In [18]:
array_float1 = np.array([1.9, 2.1, 3.1])
array_int2= array_float1.astype('int64')
print(array_int2, array_int2.dtype)

[1 2 3] int64


##ndarray 생성

In [19]:
sequence_array = np.arange(10)  
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [20]:
zero_array = np.zeros((3,3),dtype='int32')  
print(zero_array)
print(zero_array.dtype, zero_array.shape)   
print('\n')

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32 (3, 3)




In [21]:
one_array = np.ones((3,3))  
print(one_array)
print(one_array.dtype, one_array.shape)
print('\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64 (3, 3)




In [22]:
one_array = np.ones((3,3), dtype=int)  
print(one_array)
print(one_array.dtype, one_array.shape)
print('\n')

[[1 1 1]
 [1 1 1]
 [1 1 1]]
int64 (3, 3)




In [23]:
unit_array = np.eye(3)  
print(unit_array)
print(unit_array.dtype, unit_array.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
float64 (3, 3)


##ndarray의 차원, 크기 변경

In [24]:
array1 = np.arange(10)
print('array1:\n', array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [25]:
array2 = array1.reshape(2,5)
print('\n array2:\n',array2)


 array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [26]:
array3 = array1.reshape(5,2)
print('\n array3:\n',array3)


 array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
array2 = array1.reshape(-1,5)   
print('\n array2:\n',array2)
print('array2 shape:',array2.shape)


 array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array2 shape: (2, 5)


In [29]:
array3 = array1.reshape(5,-1)  
print('\n array3:\n',array3)
print('array3 shape:',array3.shape)


 array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3 shape: (5, 2)


In [30]:
array4 = array1.reshape(2,-1)  
print('\n array4:\n',array4)
print('array4 shape:',array4.shape)


 array4:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array4 shape: (2, 5)


In [31]:
array1 = np.arange(8)
print(array1)

[0 1 2 3 4 5 6 7]


In [32]:
array3d = array1.reshape((2,2,2))  
print('array3d:\n',array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [33]:
array5 = array3d.reshape(-1,1)   
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [34]:
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [35]:
array7 = array4.reshape(-1,1)
print('array7:\n',array7.tolist())
print('array7 shape:',array6.shape)

array7:
 [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]
array7 shape: (8, 1)


##Indexing

In [36]:
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

array1: [1 2 3 4 5 6 7 8 9]


In [37]:
value = array1[2]
print('value:',value)
print(type(value))

value: 3
<class 'numpy.int64'>


In [38]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [39]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [40]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0])
print('(row=0,col=1) index 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


##Slicing

In [41]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [43]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

[1 2 3]


In [44]:
array5 = array1[3:]
print(array5)

[4 5 6 7 8 9]


In [45]:
array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]


In [46]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [47]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


####fancy indexing

In [48]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

print(array1d)
print('\n', array2d)

[1 2 3 4 5 6 7 8 9]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array2d[[0,1], 2] =>  [3, 6]


In [50]:
array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]


In [51]:
array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [52]:
array6 = array2d[0,[0,1]]
print('array2d[0,[0,1]] => ',array6.tolist())

array2d[0,[0,1]] =>  [1, 2]


####Boolean indexing

In [53]:
array1d = np.arange(start=1, stop=10)

In [54]:
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [55]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [56]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [57]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]
